### PR TITLE
Fix error in parsing gzip file

### PR DESCRIPTION
**Pull request by y9c**
close https://github.com/smithlabcode/falco/issues/47

### CODE REVIEW

**Comment by y9c** [comment]
test file:

[test.fq.gz](https://github.com/smithlabcode/falco/files/11729932/test.fq.gz)

**Comment by andrewdavidsmith** [comment]
@y9c This PR has been sitting here for a while. Is it still relevant? If so, I'll take a look.

**Comment by y9c** [comment]
yes. Thank you

**Comment by andrewdavidsmith** [comment]
@y9c You pushed a binary into your pr.

**Pull request merged**
